#!/bin/bash
ip netns del client 2>/dev/null
ip netns del router 2>/dev/null
ip netns del server 2>/dev/null

echo "[*] Creating Network Namespaces..."
ip netns add client
ip netns add router
ip netns add server

echo "[*] Creating Virtual Ethernet (veth) links..."
ip link add veth-c type veth peer name veth-rc
ip link set veth-c netns client
ip link set veth-rc netns router

ip link add veth-rs type veth peer name veth-s
ip link set veth-rs netns router
ip link set veth-s netns server

echo "[*] Assigning IP addresses..."
ip netns exec client ip addr add 10.0.1.2/24 dev veth-c
ip netns exec client ip link set veth-c up
ip netns exec client ip link set lo up
ip netns exec client ip route add default via 10.0.1.1

ip netns exec router ip addr add 10.0.1.1/24 dev veth-rc
ip netns exec router ip addr add 10.0.2.1/24 dev veth-rs
ip netns exec router ip link set veth-rc up
ip netns exec router ip link set veth-rs up
ip netns exec router ip link set lo up
ip netns exec router sysctl -w net.ipv4.ip_forward=1 >/dev/null

ip netns exec server ip addr add 10.0.2.2/24 dev veth-s
ip netns exec server ip link set veth-s up
ip netns exec server ip link set lo up
ip netns exec server ip route add default via 10.0.2.1

echo "[+] Topology Ready: Client (10.0.1.2) -> Router -> Server (10.0.2.2)"
